ganhahora= float(input('Informe o valor que voce ganha por hora trabalhada:'))
horatrab= float(input('Informe quantas horas você trabalha:'))
salarioB=(horatrab*ganhahora)
ir=(salarioB*0.11)
inss=(salarioB*0.08)
sindicato=(salarioB*0.5)
salarioL=(salarioB-ir-inss-sindicato)
print('O seu salário bruto é:', salarioB)
print('O desconto do Imposto de renda é:', ir)
print('O desconto do INSS é:', inss)
print('O desconto do Sindicato é:', sindicato)
print('O seu salário líquido é:', salarioL)
