salario=float(input('Informe o seu salário:'))
if salario<=280.00:
    aumento=(salario*0.20)
    novosalario=(salario+(salario*0.20))
    print('Seu salário antes do reajuste é de:', salario)
    print('O percentual de aumento é de 20%')
    print('O valor do aumento é de:', aumento)
    print('Seu novo salário é de:', novosalario)
elif salario>280.00 or salario<700.00:
    aumento=(salario*0.15)
    novosalario=(salario+(salario*0.15))
    print('Seu salário antes do reajuste é de:', salario)
    print('O percentual de aumento é de 15%')
    print('O valor do aumento é de:', aumento)
    print('Seu novo salário é de:', novosalario)
elif salario>=700.00 or salario<1500.00:
    aumento=(salario*0.10)
    novosalario=(salario+(salario*0.10))
    print('Seu salário antes do reajuste é de:', salario)
    print('O percentual de aumento é de 10%')
    print('O valor do aumento é de:', aumento)
    print('Seu novo salário é de:', novosalario)
elif salario>=1500.00:
    aumento=(salario*0.05)
    novosalario=(salario+(salario*0.05))
    print('Seu salário antes do reajuste é de:', salario)
    print('O percentual de aumento é de 5%')
    print('O valor do aumento é de:', aumento)
    print('Seu novo salário é de:', novosalario)
