frase=input('Informe uma frase para transformar:')
frase= frase.replace('a','4')
frase= frase.replace('b','3')
frase= frase.replace('c','(')
frase= frase.replace('d','|)')
frase= frase.replace('e','&')
frase= frase.replace('f','|=')
frase= frase.replace('g','6')
frase= frase.replace('h','#')
frase= frase.replace('i','!')
frase= frase.replace('j','|')
frase= frase.replace('k','|<')
frase= frase.replace('l','1')
frase= frase.replace('m','^^')
frase= frase.replace('n','^/')
frase= frase.replace('o','0')
frase= frase.replace('p','|*')
frase= frase.replace('q','9')
frase= frase.replace('r','|2')
frase= frase.replace('s','5')
frase= frase.replace('t','7')
frase= frase.replace('u','(_)')
frase= frase.replace('v','\/')
frase= frase.replace('w','\^/')
frase= frase.replace('x','><')
frase= frase.replace('y','\-/')
frase= frase.replace('z','2')
print(frase)

